<?php
/**
 * Copyright © Itonomy BV. All rights reserved.
 * See LICENSE.md for license details.
 */

/** @var Itonomy\Flowbox\Block\Checkout\Onepage\Success $block */
?>
<?php if ($block->isFlowboxEnabled()): ?>
<div id="flowbox" data-bind="scope: 'flowbox'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#flowbox": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "flowbox-checkout": {
                            "component": "Itonomy_Flowbox/js/checkout",
                            "config": <?= /* @escapeNotVerified */ $block->getJsConfig() ?>,
                            "dataScope": "flowbox"
                        }
                    }
                }
            }
        }
    </script>
</div>
<?php endif; ?>
