<?php
/**
 * Copyright © Itonomy BV. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Itonomy\Flowbox\Block\Widget\Flow $block */
?>
<?php if ($block->isFlowboxEnabled()): ?>
<div id="flowbox" data-bind="scope: 'flowbox'" class="flowbox">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#flowbox": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "flowbox": {
                            "component": "Itonomy_Flowbox/js/flowbox",
                            "config": <?= $block->getJsConfig() ?>,
                            "dataScope": "flowbox"
                        }
                    }
                }
            }
        }
    </script>
</div>
<?php endif; ?>
