<?php
/** @var Itonomy\Flowbox\Block\Widget\Flow $block */
// TODO: Move everything inside flowbox-container to KO templates/components.
?>
<div class="flowbox-container">
    <div data-mage-init='{"flowbox-flow":<?= $block->getJsConfig() ?>}' class="flowbox flow-container">
        <div data-mage-init='{"flowbox-tagbar":{"todo":1}}' class="flowbox tagbar-container"></div>
        <div class="flowbox flow"></div>
    </div>
</div>
