<?php
/** @var Itonomy\Flowbox\Block\Widget\Flow $block */
?>
<?php if ($block->isFlowboxEnabled()): ?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "flowbox": {
                    "component": "Itonomy_Flowbox/js/flowbox",
                    "config": <?= $block->getJsConfig() ?>,
                    "dataScope": "flowbox"
                }
            }
        }
    }
}
</script>
<div data-bind="scope: 'flowbox'" id="flowbox" class="flowbox">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<?php endif; ?>
