<?php declare(strict_types=1);

namespace Itonomy\Flowbox\Block\Widget;

class Flow extends \Magento\Framework\View\Element\Template implements \Magento\Widget\Block\BlockInterface
{
    const ENABLE = 'itonomy_flowbox/general/enable';

    protected $_template = "widget/flowbox.phtml";

    /**
     * @var \Magento\Framework\Locale\ResolverInterface
     */
    private $localeResolver;
    /**
     * @var \Magento\InventoryCatalogApi\Model\GetSkusByProductIdsInterface
     */
    private $getSkusByProductIds;

    public function __construct(
        \Magento\Framework\Locale\ResolverInterface $localeResolver,
        \Magento\InventoryCatalogApi\Model\GetSkusByProductIdsInterface $getSkusByProductIds,
        \Magento\Framework\View\Element\Template\Context $context,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->getSkusByProductIds = $getSkusByProductIds;
        $this->localeResolver = $localeResolver;
    }

    /**
     * Checks if module is enabled
     * @return bool
     */
    public function isFlowboxEnabled(): bool
    {
        return $this->_scopeConfig->isSetFlag(self::ENABLE);
    }

    /**
     * Returns data for js widget
     * @return string
     */
    public function getJsConfig(): string
    {
        $this->prepareData();
        return $this->toJson(['flow', 'config']);
    }

    /**
     * Prepares data for js widget
     */
    private function prepareData()
    {
        if ($this->hasData('config')) {
            return;
        }

        $this->setData('enable', (int) $this->isFlowboxEnabled());

        // Container ID is generated by javascript.
        $config = [
            'key' => $this->getData('key'),
            'locale' => $this->getLocalePrefix(),
        ];

        $flow = $this->getFlow();
        if ($flow === 'dynamic-product') {
            $config['productId'] = $this->getProductId();
        }
        if ($flow === 'dynamic-tag') {
            $config['tags'] = $this->getTags();
            $config['tagsOperator'] = $this->getData('tags_operator');
        }
        $config['show_tag_bar'] = $this->getData('show_tag_bar');
        $this->setData('config', $config);
    }

    /**
     * @return string
     */
    private function getFlow(): string
    {
        if (!$this->hasData('flow')) {
            $this->setData('flow', 'default');
        }
        return (string) $this->getData('flow');
    }

    /**
     * @return array
     */
    private function getTags(): array
    {
        return \explode(
            ',',
            \preg_replace(
                '/\s+/',
                '',
                (string) $this->getData('tags')
            )
        );
    }

    /**
     * @return string|null
     */
    private function getProductId(): ?string
    {
        $sku = $this->getData('product_id');
        if (\is_string($sku) && \strlen($sku)) {
            return $sku;
        }
        $productId = $this->getRequest()->getParam('id');
        $sku = $this->getSkuByProductId($productId);
        if (\is_string($sku) && \strlen($productId)) {
            return $sku;
        }
        return null;
    }

    /**
     * @return string
     */
    private function getLocalePrefix(): string
    {
        return (string) $this->pageConfig->getElementAttribute('html', 'lang');
    }

    /**
     * @param $productId
     * @return string|null
     */
    private function getSkuByProductId($productId): ?string
    {
        try {
            $skus = $this->getSkusByProductIds->execute([$productId]);
        } catch (\Exception $e) {
            $skus = [null];
        }
        return \reset($skus);
    }
}
